name: REAL_FORKED_Bioinfo_project
channels:
   - conda-forge
   - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
<<<<<<< HEAD
  - pip:
      - intervaltree
=======
>>>>>>> ATAC-seq-wrangling
  - anndata
  - jupyter
  - numpy
  - seaborn
  - matplotlib
  - scanpy
  - pandas
  - openpyxl
<<<<<<< HEAD
  - git
  - git-lfs
  - intervaltree
  - umap-learn
  
=======


>>>>>>> ATAC-seq-wrangling
