name: REAL_FORKED_Bioinfo_project
channels:
   - conda-forge
   - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
<<<<<<< HEAD
=======
  - pip:
      - intervaltree
>>>>>>> 4e8f3f7767d7a49ac29935e44c375238b13a6ad0
  - anndata
  - jupyter
  - numpy
  - seaborn
  - matplotlib
  - scanpy
  - pandas
  - openpyxl
  - git
  - git-lfs
<<<<<<< HEAD
=======
  - intervaltree
  - umap-learn
>>>>>>> 4e8f3f7767d7a49ac29935e44c375238b13a6ad0
  