name: REAL_FORKED_Bioinfo_project
channels:
   - conda-forge
   - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - pip:
      - intervaltree
  - anndata
  - jupyter
  - numpy
  - seaborn
  - matplotlib
  - scanpy
  - pandas
  - openpyxl
  - git
  - git-lfs
<<<<<<< HEAD
=======
  - intervaltree
  - umap-learn
>>>>>>> fb12fdb94dca09fd32886ffaedcd3af503f7e542
  